name: Tests
on: push
jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04']
        elixir: ['1.12.x', '1.13.x']
        otp: ['23.x', '24.x']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Build cache
        uses: actions/cache@v2
        with:
          path: _build
          key: build-${{ matrix.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('lib/**/*.ex*') }}
          restore-keys: |
            build-${{ matrix.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('lib/**/*.ex*') }}
            build-${{ matrix.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-

      - name: Dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: mix-${{ matrix.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            mix-${{ matrix.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
            mix-${{ matrix.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-

      - name: Check formatting
        run: mix format --check-formatted

      - name: Fetch deps
        run: mix deps.get

      - name: Compile dev
        run: mix compile --warnings-as-errors

      - name: Run credo
        run: mix credo

      # TODO
      # - name: Compile test
      #   run: MIX_ENV=test mix compile --warnings-as-errors

      # - name: Run tests
      #   run: mix test

      # Don't cache PLTs based on mix.lock hash, as Dialyzer can incrementally update even old ones
      # Cache key based on Elixir & Erlang version (also usefull when running in matrix)
      - name: Restore PLT cache
        uses: actions/cache@v2
        id: plt_cache
        with:
          path: priv/plts
          key: plt-${{ matrix.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}
          restore-keys: |
            plt-${{ matrix.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}

      # Create PLTs if no cache was found
      - name: Create PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true' && ${{ matrix.otp != '23.x' }}
        run: mix dialyzer --plt

      - name: Run dialyzer
        if: ${{ matrix.otp != '23.x' }}
        run: mix dialyzer --list-unused-filters --format short
